/**
 * Wraps RTCPeerConnectionIceEvent generated by ICE gatherng process.
 * Calling ready() on the event will explicitly terminate ICE gathering, and
 * will initiate SDP offer/answer generation with the current collection
 * of candidates. Can be used to reduce ICE gathering delays - for example by
 * triggering termination when a suitable publicly routable srflx or relay
 * candidate is received, without the need to wait for generation of other
 * candidates.
 */
export interface RTCPeerConnectionIceEventEx {
  innerEvent: RTCPeerConnectionIceEvent;
  ready(): void;
}
